database={
    "artist_name":{
        "branch":"CSE-18",
        "instagram":"#",
        "facebook":"#",
        "profile_url":"#",
        "images_url":[
            {
                "url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
                "likes":0,
            },
            {
                "url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
                "likes":0,
            },
            {
                "url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
                "likes":0,
            },
            {
                "url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
                "likes":0,
            },
            {
                "url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
                "likes":0,
            },
            {
                "url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
                "likes":0,
            }
        ]
    },
    "artist_name_2":{
        "branch":"ECE-18",
        "instagram":"#",
        "facebook":"#",
        "profile_url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
        "images_url":[
            {
                "url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
                "likes":0,
            },
            {
                "url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
                "likes":0,
            },
            {
                "url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
                "likes":0,
            },
            {
                "url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
                "likes":0,
            },
            {
                "url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
                "likes":0,
            }
        ]
    },
    "artist_name_3":{
        "branch":"ECE-18",
        "instagram":"#",
        "facebook":"#",
        "profile_url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
        "images_url":[
            {
                "url":"https://res.cloudinary.com/dwdpobo0h/image/upload/v1607710395/sample.jpg",
                "likes":0,
            }
        ]
    },
}